# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt

# enabling search
# for more info on config see: https://docs.readthedocs.io/en/stable/config-file/v2.html#search
search:
  ranking:
    api/v1/*: -1
    api/v2/*: 4
  ignore: #list ignored pages
    - 404.html