site_name: eScriptorium Tutorial

repo_url: https://github.com/alix-tz/escriptorium-tutorial/
site_description: A collaborative tutorial to use the eScriptorium application.

# Documentation layout
#site_url: https://example.com/foo/

nav:
    - Home: index.md
    - Contributing: contribute.md
    - About: about.md


theme:
    name: readthedocs
    locale: en
    prev_next_buttons_location: both
    navigation_depth: 3
    logo: img/logo_esriptorium_tutorial.png

markdown_extensions:
    - abbr
    - admonition
    - footnotes
    - md_in_html
    - sane_lists
    - smarty
    - tables
    - toc