site_name: eScriptorium Documentation

repo_url: https://github.com/alix-tz/escriptorium-documentation/
edit_uri: edit/main/docs/
site_description: A collaborative documentation to use the eScriptorium application.

theme:
    name: readthedocs
    locale: en
    prev_next_buttons_location: both
    navigation_depth: 3
    logo: img/logo_escriptorium_documentation.png

markdown_extensions:
    - abbr
    - admonition
    - footnotes
    - md_in_html
    - sane_lists
    - smarty
    - tables
    - toc: 
        permalink: true
    - pymdownx.details
    - pymdownx.smartsymbols
    - pymdownx.highlight:
        linenums: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.keys:
        separator: "\uff0b"
        key_map: {
                'alt': '⎇ ALt',
                'left-alt': '⎇ Left ALt',
                'right-alt': '⎇ Right ALt',
                'command': '⌘ Command',
                'left-command': '⌘ Command',
                'right-command': '⌘ Command',
                'control': '⌃Ctrl',
                'left-control': '⌃Ctrl',
                'right-control': '⌃Ctrl',
                'shift': '⇧ Shift',
                'left-shift': '⇧ Left Shift',
                'right-shift': '⇧ Right Shift',
                'windows': '⊞ Win',
                'left-windows': '⊞ Win',
                'right-windows': '⊞ Win',
                'arrow-down': '↓ Down',
                'arrow-left': '← Left',
                'arrow-right': '→ Right',
                'arrow-up': '↑ Up',
                'backspace': '⌫ Backspace',
                'backtab': '⇤ Back Tab',
                'caps-lock': '⇪ Caps Lock',
                'clear': '⌧ Clr',
                'delete': '⌦ Del',
                'end': '⤓ End',
                'escape': '⎋ Esc',
                'home': '⤒ Home',
                'page-down': '⇟ Page Down',
                'page-up': '⇞ Page Up',
                'tab': 'Tab ⇥',
                'enter': 'Enter ⏎',
                'left-button': '→🖰 Left Click',
                'right-button': '🖰← Right Click'
            }

extra_css:
  - src/css/extra.css

extra_javascript:
  - src/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Contribute to the documentation: contribute.md
    - About this documentation: about.md
    - Quick-start:
        - Quick-start: quick-start.md
        - Terminology: terminology.md
        - FAQ : FAQ.md
    - Walkthrough: 
        - "Import data": import.md
        - "Automatic prediction": predict.md
        - "Manual segmentation": segment.md
        - "Manual transcription": transcribe.md
        - "Manual annotation": annotate.md
        - "Virtual keyboard": virtual_keyboard.md
        - "Train models": train.md
        - "Export data": export.md
        - "Collaborate with other users": collaborate.md
        - "Manage documents with tags": tags.md
        - "Search": search.md
        - "User-related features": users.md
        - "eScriptorium's API": api.md
        - "Administrators": administrators.md
        